ADD_RULE: ""
ADD_TAG: config-rule
RECONNECT_COUNT: 1
REMOVE_RULE: ""
UI_CHANNEL_ID: "943008506397749258"
account_to_query: axelofwar
aggregated_table_name: users_table
chat_channel_id: "943011412219920415"
collections:
  - y00ts
  - degods
data_channel_id: "943008506397749258"
db_name: community_gamification
metrics_table_name: metrics_table
pfp_table_name: pfp_table
timeout: 5
tweet_history: 15
